import { readFileSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dist = resolve(__dirname, 'dist');

// JS map: { "primary": "var(--primary)", ... } + a readonly name list.
StyleDictionary.registerFormat({
  name: 'surf/tokens-js',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens.map((t) => `  "${t.name}": "var(--${t.name})"`);
    const names = dictionary.allTokens.map((t) => `"${t.name}"`);
    return [
      '// Auto-generated by style-dictionary.config.js — do not edit manually.',
      `export const tokens = {\n${entries.join(',\n')}\n};`,
      '',
      `export const tokenNames = /** @type {const} */ ([${names.join(', ')}]);`,
      '',
    ].join('\n');
  },
});

// Matching .d.ts: TokenName union derived from the same source.
StyleDictionary.registerFormat({
  name: 'surf/tokens-dts',
  format: ({ dictionary }) => {
    const union = dictionary.allTokens.map((t) => `  | '${t.name}'`).join('\n');
    return [
      '// Auto-generated by style-dictionary.config.js — do not edit manually.',
      `export type TokenName =\n${union};`,
      '',
      'export declare const tokens: Record<TokenName, string>;',
      'export declare const tokenNames: readonly TokenName[];',
      '',
    ].join('\n');
  },
});

/** Build one mode (light/dark) into a CSS fragment under the given selector. */
async function buildMode({ source, selector, cssFile, extraFiles = [] }) {
  const sd = new StyleDictionary({
    source: [resolve(__dirname, source)],
    platforms: {
      surf: {
        // Built-in name transform only — no color transform, so oklch(...) values
        // pass through verbatim. Flat kebab keys come out unchanged.
        transforms: ['name/kebab'],
        buildPath: 'dist/',
        files: [
          {
            destination: cssFile,
            format: 'css/variables',
            options: { selector, outputReferences: true, showFileHeader: false },
          },
          ...extraFiles,
        ],
      },
    },
  });
  await sd.buildAllPlatforms();
}

// Light also emits the JS map + type union (token names are mode-independent).
await buildMode({
  source: 'src/tokens.json',
  selector: ':root',
  cssFile: 'tokens.light.css',
  extraFiles: [
    { destination: 'index.js', format: 'surf/tokens-js' },
    { destination: 'index.d.ts', format: 'surf/tokens-dts' },
  ],
});

await buildMode({
  source: 'src/tokens.dark.json',
  selector: '.dark',
  cssFile: 'tokens.dark.css',
});

// Combine the two mode fragments into the single shipped tokens.css.
const light = readFileSync(resolve(dist, 'tokens.light.css'), 'utf8').trimEnd();
const dark = readFileSync(resolve(dist, 'tokens.dark.css'), 'utf8').trimEnd();
writeFileSync(resolve(dist, 'tokens.css'), `${light}\n\n${dark}\n`, 'utf8');
rmSync(resolve(dist, 'tokens.light.css'));
rmSync(resolve(dist, 'tokens.dark.css'));

console.log('Built dist/tokens.css, dist/index.js, dist/index.d.ts via Style Dictionary');
